export interface User {
    id: number,
    hash: string,
    name: string,
    surname: string,
    email: string,
    facebook: string,
    linkedin: string,
    date_insert: string,
    status: number,
    twitter: string,
    password: string,
    telephone: string,
    instagram: string,
    whatsapp: string,
    telegram: string,
    tiktok: string,
    spotify: string,
    youtube: string,
    wildcard_1: string,
    wildcard_2: string,
    wildcard_3: string,
    end_city: string,
    end_number: string,
    end_district: string,
    end_cep: string,
    imageUrl: string
}

export const UserValue: User = {
    id: 1,
    hash: '',
    name: '',
    surname: '',
    email: '',
    facebook: '',
    linkedin: '',
    date_insert: '',
    status: 0,
    twitter: '',
    password: '',
    telephone: '',
    instagram: '',
    whatsapp: '',
    telegram: '',
    tiktok: '',
    spotify: '',
    youtube: '',
    wildcard_1: '',
    wildcard_2: '',
    wildcard_3: '',
    end_city: '',
    end_number: '',
    end_district: '',
    end_cep: '',
    imageUrl: ''
}